export const Commands = {
  GetBootstrap: "get_bootstrap",
  GetPod: "get_pod",
  GetMonitors: "get_monitors",
  GetModifierState: "get_modifier_state",
  GetHotkeyDefaults: "get_hotkey_defaults",
  CreatePod: "create_pod",
  UpdatePod: "update_pod",
  DeletePod: "delete_pod",
  SaveSettings: "save_settings",
  HoldPendingDrop: "hold_pending_drop",
  StagePaths: "stage_paths",
  StageText: "stage_text",
  ListPodItems: "list_pod_items",
  RemoveItems: "remove_items",
  ExportItems: "export_items",
  PrepareDragCut: "prepare_drag_cut",
  FinalizeDragCut: "finalize_drag_cut",
  CancelDragCut: "cancel_drag_cut",
  ReadThumbnail: "read_thumbnail",
  ShowPanel: "show_panel",
  TogglePanel: "toggle_panel",
  HidePanel: "hide_panel",
  SetPanelMode: "set_panel_mode",
  GetPanelState: "get_panel_state",
  ReportPresence: "report_presence",
  SetPanelPinned: "set_panel_pinned",
  SetDraggingOut: "set_dragging_out",
  SetPodAccept: "set_pod_accept",
  SetPanelSize: "set_panel_size",
  MovePodBar: "move_pod_bar",
  ToggleAllBars: "toggle_all_bars",
  OpenSettings: "open_settings",
  LogFrontend: "log_frontend",
  AppLog: "app_log",
  QuitApp: "quit_app",
} as const;

export type CommandName = (typeof Commands)[keyof typeof Commands];
