export const Events = {
  ItemsChanged: "floepod://items-changed",
  SettingsChanged: "floepod://settings-changed",
  PodsChanged: "floepod://pods-changed",
  PanelMode: "floepod://panel-mode",
  PanelShown: "floepod://panel-shown",
  PanelPinned: "floepod://panel-pinned",
  PanelState: "floepod://panel-state",
  PanelHidden: "floepod://panel-hidden",
  CollectClipboard: "floepod://collect-clipboard",
  RequestFilePicker: "floepod://request-file-picker",
  PodLockChanged: "floepod://pod-lock-changed",
  BarStealth: "floepod://bar-stealth",
  ContextMenuShow: "floepod://context-menu-show",
  ContextMenuChoice: "floepod://context-menu-choice",
  ContextMenuClosed: "floepod://context-menu-closed",
} as const;
