// Generated from Rust signatures and Serde schemas. Run pnpm ipc:generate; do not edit.
export type Accessibility = { "confirmDangerous": boolean; "highContrast": boolean; "reduceMotion": boolean; "reduceTransparency": boolean; "scale": number; "sendToMenu": boolean; "simpleLanguage": boolean; };
export type Annotation = { "note": string; "tags": Array<string>; };
export type AutoBlock = { "apps": Array<string>; "enabled": boolean; };
export type Bootstrap = { "monitors": Array<MonitorInfo>; "settings": Settings; "version": string; };
export type CleanResult = { "output": string; "removed": Array<string>; "source": string; "warnings": Array<string>; };
export type ExportedArtifact = { "path": string; "records": number; };
export type ExportIssue = { "error": string; "id": number; "name": string; };
export type ExportResult = { "completedIds": Array<number>; "conflicts": Array<string>; "failed": Array<ExportIssue>; "skippedIds": Array<number>; "staleIds": Array<number>; "warnings": Array<ExportIssue>; };
export type HandoffFile = { "cleaned": Array<string>; "relativePath": string; "sha256": string; "size": number; "source": string; };
export type HandoffResult = { "directory": string; "files": Array<HandoffFile>; "missing": Array<string>; "warnings": Array<string>; };
export type Hotkeys = { "collectClipboard": string; "lockSensitive": string; "openPanel": string; "toggleBar": string; };
export type IndexResult = { "failures": Array<string>; "indexed": number; "ocrAvailable": boolean; "skipped": number; };
export type MenuChoice = { "action": MenuItemSpec; "podId": number; };
export type MenuItemSpec = { "danger": boolean; "disabled": boolean; "id": string; "itemIds": Array<number>; "label": string; "separator": boolean; "text": string; };
export type MenuShow = { "items": Array<MenuItemSpec>; "material": "plain" | "acrylic"; "podId": number; "seq": number; };
export type MetadataCheck = { "path": string; "reason": string | null; "status": ScanStatus; };
export type ModeChanged = { "mode": "list" | "ask" | "conflict"; "paths": Array<string>; };
export type ModifierState = { "alt": boolean; "ctrl": boolean; "shift": boolean; };
export type MonitorInfo = { "height": number; "label": string; "name": string; "primary": boolean; "scaleFactor": number; "width": number; "x": number; "y": number; };
export type OperationEntry = { "createdAt": number; "id": number; "items": Array<OperationItemEntry>; "kind": string; "podId": number | null; "retryable": boolean; "status": string; "summary": string; "undoable": boolean; "undoableUntil": number | null; "undoneAt": number | null; };
export type OperationItemEntry = { "action": string; "error": string | null; "id": number; "itemId": number | null; "name": string; "sourcePath": string | null; "status": string; "targetPath": string | null; };
export type OperationPreview = { "details": Array<string>; "requiresConfirmation": boolean; "title": string; "warnings": Array<string>; };
export type OrganizationPolicy = { "allowedDataRoots": Array<string>; "diagnosticIncludePaths": boolean; "disableFulltextIndex": boolean; "disableMove": boolean; "lockRules": boolean; "managedHotkeys": (Hotkeys) | (null); "managedPods": Array<Pod>; "mandatoryRetentionDays": number; "maximumHistoryDays": number; "organizationName": string; "requireCopyDefault": boolean; "requirePrivacyScan": boolean; "supportContact": string; };
export type PanelSnapshot = { "draggingOut": boolean; "mode": "list" | "ask" | "conflict"; "paths": Array<string>; "pinned": boolean; "visible": boolean; };
export type PinnedChanged = { "pinned": boolean; };
export type Pod = { "autoHide": boolean; "autoHideDelayMs": number; "barColor": string; "barLength": number; "barWidth": number; "borderColor": string; "borderOpacity": number; "cornerRadius": number; "dropAction": "ask" | "copy" | "move" | "shortcut"; "edge": "top" | "right" | "bottom" | "left"; "enabled": boolean; "hoverDelayMs": number; "hoverOpen": boolean; "id": number; "material": "plain" | "acrylic"; "monitor": string; "name": string; "offset": number; "opacity": number; "panelColor": string; "panelMaterial": "plain" | "acrylic"; "panelOpacity": number; "panelWidth": number; "rules": PodRules; "security": PodSecurity; "stagingFolder": string; "stealth": boolean; "stealthDelayMs": number; };
export type PodEvent = { "podId": number; };
export type PodLockChanged = { "locked": boolean; "podId": number; };
export type PodRules = { "allowedExtensions": Array<string>; "checksumSidecar": boolean; "duplicatePolicy": "allow" | "reject"; "enabled": boolean; "expireDays": number; "maxSizeMb": number; "nameContains": string; "removeAfterExport": boolean; "renamePattern": string; "sourceFolder": string; "subfolderPattern": string; "template": string; };
export type PodSecurity = { "autoLockMinutes": number; "cleanupAfterExport": boolean; "enabled": boolean; "requireWindowsHello": boolean; "retentionDays": number; "suppressIndex": boolean; "suppressThumbnails": boolean; };
export type PolicyStatus = { "managed": boolean; "policy": OrganizationPolicy; "source": string | null; };
export type PrivacyIssue = { "canClean": boolean; "code": string; "message": string; "path": string; "severity": string; };
export type PrivacyScanResult = { "disclaimer": string; "duplicates": Array<Array<string>>; "files": Array<MetadataCheck>; "filesChecked": number; "filesFailed": number; "filesScanned": number; "filesSkipped": number; "issues": Array<PrivacyIssue>; };
export type RetryResult = { "kind": string; "operationId": number; "result": unknown; };
export type SafeExportResult = { "completed": Array<CleanResult>; "failed": Array<string>; };
export type ScanStatus = "checked" | "skipped" | "failed";
export type SearchHit = { "item": StagedItem; "matchedOn": Array<string>; "note": string; "snippet": string; "tags": Array<string>; };
export type SecurityStatus = { "efsEncrypted": boolean; "expiresSoon": number; "locked": boolean; "podId": number; "sensitive": boolean; };
export type Settings = { "accessibility": Accessibility; "autoBlock": AutoBlock; "autostart": boolean; "dataDir": string; "firstRunDone": boolean; "hotkeys": Hotkeys; "pods": Array<Pod>; "theme": "system" | "light" | "dark"; "version": string; };
export type StagedItem = { "createdAt": number; "ext": string | null; "id": number; "kind": "file" | "folder" | "text" | "shortcut"; "name": string; "originalPath": string | null; "podId": number; "size": number; "stagingPath": string; };
export type StagePathsResult = { "items": Array<StagedItem>; "warnings": Array<StageWarning>; };
export type StageWarning = { "error": string; "name": string; };
export type StealthChanged = { "hidden": boolean; };
export type ThumbnailPayload = { "bytes": Array<number>; "mime": string; };
export type UndoResult = { "failed": Array<string>; "operationId": number; "restored": number; };
export type VerifyIssue = { "actual": string | null; "expected": string; "path": string; };
export type VerifyResult = { "checked": number; "issues": Array<VerifyIssue>; "valid": number; };

export interface CommandContract {
  "app_log": { args: { "msg": string; }; result: void };
  "cancel_drag_cut": { args: { "token": string; }; result: void };
  "context_menu_choice": { args: { "action": { "danger"?: boolean; "disabled"?: boolean; "id": string; "itemIds"?: Array<number>; "label"?: string; "separator"?: boolean; "text"?: string; }; "podId": number; "seq": number; }; result: void };
  "context_menu_ready": { args: {  }; result: void };
  "copy_staged_to_clipboard": { args: { "itemIds": Array<number>; }; result: void };
  "create_handoff": { args: { "cleanMetadata": boolean; "destDir": string; "ids": Array<number>; "note": string; "title": string; }; result: { "directory": string; "files": Array<HandoffFile>; "missing": Array<string>; "warnings": Array<string>; } };
  "create_pod": { args: { "config": { "autoHide"?: boolean; "autoHideDelayMs"?: (number) | (string); "barColor"?: string; "barLength"?: (number) | (string); "barWidth"?: (number) | (string); "borderColor"?: string; "borderOpacity"?: (number) | (string); "cornerRadius"?: (number) | (string); "dropAction"?: "ask" | "copy" | "move" | "shortcut"; "edge"?: "top" | "right" | "bottom" | "left"; "enabled"?: boolean; "hoverDelayMs"?: (number) | (string); "hoverOpen"?: boolean; "monitor"?: string; "name"?: string; "offset"?: (number) | (string); "opacity"?: (number) | (string); "panelColor"?: string; "panelMaterial"?: "plain" | "acrylic"; "panelOpacity"?: (number) | (string); "panelWidth"?: (number) | (string); "rules"?: { "allowedExtensions"?: Array<string>; "checksumSidecar"?: boolean; "duplicatePolicy"?: "allow" | "reject"; "enabled"?: boolean; "expireDays"?: number; "maxSizeMb"?: number; "nameContains"?: string; "removeAfterExport"?: boolean; "renamePattern"?: string; "sourceFolder"?: string; "subfolderPattern"?: string; "template"?: string; }; "security"?: { "autoLockMinutes"?: number; "cleanupAfterExport"?: boolean; "enabled"?: boolean; "requireWindowsHello"?: boolean; "retentionDays"?: number; "suppressIndex"?: boolean; "suppressThumbnails"?: boolean; }; "stagingFolder"?: string; "stealth"?: boolean; "stealthDelayMs"?: (number) | (string); }; "reuseExisting": boolean; }; result: { "autoHide": boolean; "autoHideDelayMs": number; "barColor": string; "barLength": number; "barWidth": number; "borderColor": string; "borderOpacity": number; "cornerRadius": number; "dropAction": "ask" | "copy" | "move" | "shortcut"; "edge": "top" | "right" | "bottom" | "left"; "enabled": boolean; "hoverDelayMs": number; "hoverOpen": boolean; "id": number; "material": "plain" | "acrylic"; "monitor": string; "name": string; "offset": number; "opacity": number; "panelColor": string; "panelMaterial": "plain" | "acrylic"; "panelOpacity": number; "panelWidth": number; "rules": PodRules; "security": PodSecurity; "stagingFolder": string; "stealth": boolean; "stealthDelayMs": number; } };
  "delete_pod": { args: { "mode": string; "podId": number; }; result: void };
  "dismiss_context_menu": { args: {  }; result: void };
  "export_audit_log": { args: { "destDir": string; "format": string; }; result: { "path": string; "records": number; } };
  "export_diagnostic_bundle": { args: { "destDir": string; }; result: { "path": string; "records": number; } };
  "export_items": { args: { "destDir": string; "ids": Array<number>; "mode": string; "onConflict": string; }; result: { "completedIds": Array<number>; "conflicts": Array<string>; "failed": Array<ExportIssue>; "skippedIds": Array<number>; "staleIds": Array<number>; "warnings": Array<ExportIssue>; } };
  "export_settings_file": { args: { "destDir": string; }; result: { "path": string; "records": number; } };
  "finalize_drag_cut": { args: { "token": string; }; result: void };
  "get_bootstrap": { args: {  }; result: { "monitors": Array<MonitorInfo>; "settings": Settings; "version": string; } };
  "get_hotkey_defaults": { args: {  }; result: { "collectClipboard": string; "lockSensitive": string; "openPanel": string; "toggleBar": string; } };
  "get_item_annotation": { args: { "itemId": number; }; result: { "note": string; "tags": Array<string>; } };
  "get_modifier_state": { args: {  }; result: { "alt": boolean; "ctrl": boolean; "shift": boolean; } };
  "get_organization_policy": { args: {  }; result: { "managed": boolean; "policy": OrganizationPolicy; "source": string | null; } };
  "get_panel_state": { args: { "podId": number; }; result: { "draggingOut": boolean; "mode": "list" | "ask" | "conflict"; "paths": Array<string>; "pinned": boolean; "visible": boolean; } };
  "get_pod_security_status": { args: { "podId": number; }; result: { "efsEncrypted": boolean; "expiresSoon": number; "locked": boolean; "podId": number; "sensitive": boolean; } };
  "hide_context_menu": { args: { "podId": number; "seq": number; }; result: void };
  "hide_panel": { args: { "podId": number; }; result: void };
  "hold_pending_drop": { args: { "paths": Array<string>; "podId": number; }; result: void };
  "import_settings_file": { args: { "source": string; }; result: { "accessibility": Accessibility; "autoBlock": AutoBlock; "autostart": boolean; "dataDir": string; "firstRunDone": boolean; "hotkeys": Hotkeys; "pods": Array<Pod>; "theme": "system" | "light" | "dark"; "version": string; } };
  "list_operations": { args: { "hours"?: number | null; "limit"?: number | null; }; result: Array<OperationEntry> };
  "list_pod_items": { args: { "podId": number; }; result: Array<StagedItem> };
  "lock_all_sensitive_pods": { args: {  }; result: void };
  "lock_sensitive_pod": { args: { "podId": number; }; result: void };
  "log_frontend": { args: { "msg": string; }; result: void };
  "move_pod_bar": { args: { "offset": number; "podId": number; }; result: void };
  "open_context_menu": { args: { "items": Array<{ "danger"?: boolean; "disabled"?: boolean; "id": string; "itemIds"?: Array<number>; "label"?: string; "separator"?: boolean; "text"?: string; }>; "podId": number; }; result: void };
  "open_pod_folder": { args: { "podId": number; }; result: void };
  "open_settings": { args: {  }; result: void };
  "open_staged_item": { args: { "itemId": number; }; result: void };
  "prepare_drag_cut": { args: { "paths": Array<string>; "podId": number; }; result: string };
  "preview_export_items": { args: { "destDir": string; "ids": Array<number>; "mode": string; }; result: { "details": Array<string>; "requiresConfirmation": boolean; "title": string; "warnings": Array<string>; } };
  "preview_remove_items": { args: { "deleteFiles": boolean; "ids": Array<number>; }; result: { "details": Array<string>; "requiresConfirmation": boolean; "title": string; "warnings": Array<string>; } };
  "quit_app": { args: {  }; result: void };
  "read_clipboard_files": { args: {  }; result: Array<string> };
  "read_thumbnail": { args: { "path": string; }; result: (ThumbnailPayload) | (null) };
  "rebuild_search_index": { args: { "podId"?: number | null; }; result: { "failures": Array<string>; "indexed": number; "ocrAvailable": boolean; "skipped": number; } };
  "remove_items": { args: { "deleteFiles": boolean; "ids": Array<number>; }; result: void };
  "report_presence": { args: { "inside": boolean; "podId": number; "window": string; }; result: void };
  "resize_context_menu": { args: { "height": number; "seq": number; "width": number; }; result: void };
  "retry_operation": { args: { "operationId": number; }; result: { "kind": string; "operationId": number; "result": unknown; } };
  "reveal_staged_items": { args: { "itemIds": Array<number>; }; result: void };
  "safe_export_items": { args: { "destDir": string; "ids": Array<number>; }; result: { "completed": Array<CleanResult>; "failed": Array<string>; } };
  "save_settings": { args: { "patch": { "accessibility"?: { "confirmDangerous"?: boolean; "highContrast"?: boolean; "reduceMotion"?: boolean; "reduceTransparency"?: boolean; "scale"?: number; "sendToMenu"?: boolean; "simpleLanguage"?: boolean; }; "autoBlock"?: { "apps"?: Array<string>; "enabled"?: boolean; }; "autostart"?: boolean; "dataDir"?: unknown; "firstRunDone"?: boolean; "hotkeys"?: { "collectClipboard"?: string; "lockSensitive"?: string; "openPanel"?: string; "toggleBar"?: string; }; "pods"?: unknown; "theme"?: "system" | "light" | "dark"; "version"?: unknown; }; }; result: { "accessibility": Accessibility; "autoBlock": AutoBlock; "autostart": boolean; "dataDir": string; "firstRunDone": boolean; "hotkeys": Hotkeys; "pods": Array<Pod>; "theme": "system" | "light" | "dark"; "version": string; } };
  "scan_privacy": { args: { "ids": Array<number>; }; result: { "disclaimer": string; "duplicates": Array<Array<string>>; "files": Array<MetadataCheck>; "filesChecked": number; "filesFailed": number; "filesScanned": number; "filesSkipped": number; "issues": Array<PrivacyIssue>; } };
  "search_items": { args: { "podId"?: number | null; "query": string; }; result: Array<SearchHit> };
  "set_dragging_out": { args: { "dragging": boolean; "podId": number; }; result: void };
  "set_panel_mode": { args: { "mode": string; "podId": number; }; result: void };
  "set_panel_pinned": { args: { "pinned": boolean; "podId": number; }; result: void };
  "set_panel_size": { args: { "height": number; "podId": number; }; result: void };
  "set_pod_accept": { args: { "accepting": boolean; "podId": number; }; result: void };
  "show_panel": { args: { "podId": number; }; result: void };
  "stage_paths": { args: { "action": string; "paths": Array<string>; "podId": number; }; result: { "items": Array<StagedItem>; "warnings": Array<StageWarning>; } };
  "stage_text": { args: { "content": string; "podId": number; "title"?: string | null; }; result: { "createdAt": number; "ext": string | null; "id": number; "kind": "file" | "folder" | "text" | "shortcut"; "name": string; "originalPath": string | null; "podId": number; "size": number; "stagingPath": string; } };
  "toggle_panel": { args: { "podId": number; }; result: void };
  "undo_operation": { args: { "operationId": number; }; result: { "failed": Array<string>; "operationId": number; "restored": number; } };
  "unlock_sensitive_pod": { args: { "podId": number; }; result: { "efsEncrypted": boolean; "expiresSoon": number; "locked": boolean; "podId": number; "sensitive": boolean; } };
  "update_item_annotation": { args: { "itemId": number; "note": string; "tags": Array<string>; }; result: void };
  "update_pod": { args: { "patch": { "autoHide"?: boolean; "autoHideDelayMs"?: (number) | (string); "barColor"?: string; "barLength"?: (number) | (string); "barWidth"?: (number) | (string); "borderColor"?: string; "borderOpacity"?: (number) | (string); "cornerRadius"?: (number) | (string); "dropAction"?: "ask" | "copy" | "move" | "shortcut"; "edge"?: "top" | "right" | "bottom" | "left"; "enabled"?: boolean; "hoverDelayMs"?: (number) | (string); "hoverOpen"?: boolean; "monitor"?: string; "name"?: string; "offset"?: (number) | (string); "opacity"?: (number) | (string); "panelColor"?: string; "panelMaterial"?: "plain" | "acrylic"; "panelOpacity"?: (number) | (string); "panelWidth"?: (number) | (string); "rules"?: { "allowedExtensions"?: Array<string>; "checksumSidecar"?: boolean; "duplicatePolicy"?: "allow" | "reject"; "enabled"?: boolean; "expireDays"?: number; "maxSizeMb"?: number; "nameContains"?: string; "removeAfterExport"?: boolean; "renamePattern"?: string; "sourceFolder"?: string; "subfolderPattern"?: string; "template"?: string; }; "security"?: { "autoLockMinutes"?: number; "cleanupAfterExport"?: boolean; "enabled"?: boolean; "requireWindowsHello"?: boolean; "retentionDays"?: number; "suppressIndex"?: boolean; "suppressThumbnails"?: boolean; }; "stagingFolder"?: string; "stealth"?: boolean; "stealthDelayMs"?: (number) | (string); }; "podId": number; }; result: { "autoHide": boolean; "autoHideDelayMs": number; "barColor": string; "barLength": number; "barWidth": number; "borderColor": string; "borderOpacity": number; "cornerRadius": number; "dropAction": "ask" | "copy" | "move" | "shortcut"; "edge": "top" | "right" | "bottom" | "left"; "enabled": boolean; "hoverDelayMs": number; "hoverOpen": boolean; "id": number; "material": "plain" | "acrylic"; "monitor": string; "name": string; "offset": number; "opacity": number; "panelColor": string; "panelMaterial": "plain" | "acrylic"; "panelOpacity": number; "panelWidth": number; "rules": PodRules; "security": PodSecurity; "stagingFolder": string; "stealth": boolean; "stealthDelayMs": number; } };
  "verify_handoff": { args: { "directory": string; }; result: { "checked": number; "issues": Array<VerifyIssue>; "valid": number; } };
  "write_clipboard_text": { args: { "text": string; }; result: void };
}

export interface EventContract {
  "floepod://bar-stealth": { "hidden": boolean; };
  "floepod://collect-clipboard": { "podId": number; };
  "floepod://context-menu-choice": { "action": MenuItemSpec; "podId": number; };
  "floepod://context-menu-closed": { "podId": number; };
  "floepod://context-menu-show": { "items": Array<MenuItemSpec>; "material": "plain" | "acrylic"; "podId": number; "seq": number; };
  "floepod://items-changed": { "podId": number; };
  "floepod://panel-hidden": void;
  "floepod://panel-mode": { "mode": "list" | "ask" | "conflict"; "paths": Array<string>; };
  "floepod://panel-pinned": { "pinned": boolean; };
  "floepod://panel-shown": void;
  "floepod://panel-state": { "draggingOut": boolean; "mode": "list" | "ask" | "conflict"; "paths": Array<string>; "pinned": boolean; "visible": boolean; };
  "floepod://pod-lock-changed": { "locked": boolean; "podId": number; };
  "floepod://pods-changed": void;
  "floepod://request-file-picker": { "podId": number; };
  "floepod://settings-changed": { "accessibility": Accessibility; "autoBlock": AutoBlock; "autostart": boolean; "dataDir": string; "firstRunDone": boolean; "hotkeys": Hotkeys; "pods": Array<Pod>; "theme": "system" | "light" | "dark"; "version": string; };
}
